In [1]:
import pandas as pd
df = pd.read_sas("LLCP2016.XPT", format='xport')

In [2]:
df

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_MAM5021,_RFPAP33,_RFPSA21,_RFBLDS3,_COL10YR,_HFOB3YR,_FS5YR,_FOBTFS,_CRCREC,_AIDTST3
0,1.0,1.0,b'01072016',b'01',b'07',b'2016',1100.0,b'2016000001',2.016000e+09,1.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1.0,1.0,b'01112016',b'01',b'11',b'2016',1100.0,b'2016000002',2.016000e+09,1.0,...,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,2.0
2,1.0,1.0,b'01062016',b'01',b'06',b'2016',1100.0,b'2016000003',2.016000e+09,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,1.0,1.0,b'01082016',b'01',b'08',b'2016',1100.0,b'2016000004',2.016000e+09,1.0,...,NaN,NaN,1.0,2.0,1.0,2.0,NaN,2.0,1.0,9.0
4,1.0,1.0,b'01052016',b'01',b'05',b'2016',1100.0,b'2016000005',2.016000e+09,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486298,78.0,12.0,b'12312016',b'12',b'31',b'2016',1200.0,b'2016001262',2.016001e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486299,78.0,12.0,b'12192016',b'12',b'19',b'2016',1100.0,b'2016001263',2.016001e+09,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0
486300,78.0,12.0,b'12092016',b'12',b'09',b'2016',1100.0,b'2016001264',2.016001e+09,NaN,...,2.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0
486301,78.0,12.0,b'12312016',b'12',b'31',b'2016',1200.0,b'2016001265',2.016001e+09,NaN,...,2.0,1.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,NaN
486302,78.0,12.0,b'12312016',b'12',b'31',b'2016',1200.0,b'2016001266',2.016001e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.to_csv("LLCP2016.csv", index=False)